# Helper script to visualize the problem. Generated by Haiku 4.5
# Read coordinates
coords = []
with open("input.txt", "r") as f:
    for line in f:
        x, y = map(int, line.strip().split(","))
        coords.append((x, y))

# Find bounds
min_x = min(c[0] for c in coords)
max_x = max(c[0] for c in coords)
min_y = min(c[1] for c in coords)
max_y = max(c[1] for c in coords)

width = max_x - min_x
height = max_y - min_y

# Example rectangles defined by opposite corners
best_p = [[[5025, 66513], [94997, 50126]], [[3965, 35618], [94997, 48641]]]

# Create SVG
svg = f"""<svg viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg">
<path d="M {coords[0][0] - min_x} {coords[0][1] - min_y}"""

for x, y in coords[1:]:
    svg += f" L {x - min_x} {y - min_y}"

svg += """" stroke="black" stroke-width="15" fill="none"/>
"""

# Draw rectangles
for rect in best_p:
    (x1, y1), (x2, y2) = rect
    # Normalize coordinates (top-left to bottom-right)
    left = min(x1, x2) - min_x
    top = min(y1, y2) - min_y
    rect_width = abs(x2 - x1)
    rect_height = abs(y2 - y1)

    svg += f"""<rect x="{left}" y="{top}" width="{rect_width}" height="{rect_height}" stroke="red" stroke-width="20" fill="none"/>
"""

svg += "</svg>"

# Write SVG
with open("output.svg", "w") as f:
    f.write(svg)

print("Wrote output.svg")
